// ============================================================
// openapi/openapi.ts
// Builds an OpenAPI 3.0 spec from the global registry.
// Mirror of OpenApi.init() / OpenApi.docs in Dart.
// ============================================================

import { apiRegistry } from '../core/registry';
import type { RequestHandler } from 'express';

interface OpenApiOptions {
  title: string;
  port: number;
  version?: string;
  description?: string;
  servers?: Array<{ url: string; description?: string }>;
}

/**
 * Builds a full OpenAPI 3.0 specification object from all registered use
 * cases in `apiRegistry`. Called by ModularApi.serve() automatically.
 *
 * Each use case contributes:
 *   - A path entry (e.g. POST /api/users/create)
 *   - requestBody schema from Input.toSchema()
 *   - response schema from Output.toSchema()
 *   - summary and tags from UseCaseDocMeta
 */
export function buildOpenApiSpec(options: OpenApiOptions): Record<string, unknown> {
  const {
    title,
    port,
    version = '0.1.0',
    description = 'Auto-generated by modular-api',
    servers,
  } = options;

  const defaultServers = [{ url: `http://localhost:${port}`, description: 'Local' }];

  const paths: Record<string, unknown> = {};

  for (const route of apiRegistry.routes) {
    const method = route.method.toLowerCase();
    const path = route.path;

    // Use schemas captured at registration time
    const inputSchema = route.schemas.input;
    const outputSchema = route.schemas.output;

    if (!paths[path]) {
      paths[path] = {};
    }

    (paths[path] as Record<string, unknown>)[method] = {
      summary: route.doc?.summary,
      description: route.doc?.description,
      tags: route.doc?.tags ?? [route.module],
      ...(method !== 'get' && method !== 'delete'
        ? {
            requestBody: {
              required: true,
              content: {
                'application/json': {
                  schema: inputSchema,
                },
              },
            },
          }
        : {
            parameters: _schemaToQueryParams(inputSchema),
          }),
      responses: {
        '200': {
          description: 'Successful response',
          content: {
            'application/json': {
              schema: outputSchema,
            },
          },
        },
        '400': {
          description: 'Validation error',
          content: {
            'application/json': {
              schema: {
                type: 'object',
                properties: { error: { type: 'string' } },
              },
            },
          },
        },
        '500': {
          description: 'Internal server error',
        },
      },
    };
  }

  return {
    openapi: '3.0.0',
    info: { title, version, description },
    servers: servers ?? defaultServers,
    paths,
  };
}

/** Converts a JSON Schema object properties to OpenAPI query parameters */
function _schemaToQueryParams(schema: Record<string, unknown>): unknown[] {
  const properties = (schema['properties'] as Record<string, unknown>) ?? {};
  const required = (schema['required'] as string[]) ?? [];

  return Object.entries(properties).map(([name, propSchema]) => ({
    name,
    in: 'query',
    required: required.includes(name),
    schema: propSchema,
  }));
}

// ============================================================
// JSON-to-YAML converter (zero dependencies)
// ============================================================

/** YAML reserved words that need quoting */
const YAML_RESERVED = new Set(['true', 'false', 'null', 'yes', 'no', 'on', 'off', 'y', 'n']);

/** Characters that require quoting in a YAML string value */
const YAML_SPECIAL_RE = /[:{}\[\],&*?|>!%#@`"\\]/;

/**
 * Determines if a string needs quoting in YAML.
 */
function needsQuoting(s: string): boolean {
  if (s.length === 0) return true;
  if (YAML_RESERVED.has(s.toLowerCase())) return true;
  if (YAML_SPECIAL_RE.test(s)) return true;
  if (/^[-? ]/.test(s)) return true;
  if (!isNaN(Number(s)) && s.trim().length > 0) return true;
  if (s.includes('\n')) return true;
  return false;
}

/** Formats a YAML key, quoting if necessary. */
function yamlKey(key: string): string {
  if (needsQuoting(key)) return `'${key.replace(/'/g, "''")}'`;
  return key;
}

/** Writes a scalar YAML value. */
function yamlScalar(value: unknown): string {
  if (value === null || value === undefined) return 'null';
  if (typeof value === 'boolean') return value ? 'true' : 'false';
  if (typeof value === 'number') return String(value);
  const s = String(value);
  if (needsQuoting(s)) return `'${s.replace(/'/g, "''")}'`;
  return s;
}

/**
 * Converts a JSON-decoded value to a YAML string.
 * Zero dependencies — handles objects, arrays, strings, numbers, bools, null.
 */
export function jsonToYaml(value: unknown, indent = 0, isRoot = true): string {
  const pad = '  '.repeat(indent);

  if (value !== null && typeof value === 'object' && !Array.isArray(value)) {
    const obj = value as Record<string, unknown>;
    const keys = Object.keys(obj);
    if (keys.length === 0) return '{}\n';

    let result = isRoot ? '' : '\n';
    for (const key of keys) {
      const v = obj[key];
      if (v !== null && typeof v === 'object') {
        result += `${pad}${yamlKey(key)}:${jsonToYaml(v, indent + 1, false)}`;
      } else {
        result += `${pad}${yamlKey(key)}: ${yamlScalar(v)}\n`;
      }
    }
    return result;
  }

  if (Array.isArray(value)) {
    if (value.length === 0) return '[]\n';

    let result = isRoot ? '' : '\n';
    for (const item of value) {
      if (item !== null && typeof item === 'object' && !Array.isArray(item)) {
        const entries = Object.entries(item as Record<string, unknown>);
        if (entries.length > 0) {
          let first = true;
          for (const [k, v] of entries) {
            if (first) {
              result += `${pad}- ${yamlKey(k)}:`;
              first = false;
            } else {
              result += `${pad}  ${yamlKey(k)}:`;
            }
            if (v !== null && typeof v === 'object') {
              result += jsonToYaml(v, indent + 2, false);
            } else {
              result += ` ${yamlScalar(v)}\n`;
            }
          }
        } else {
          result += `${pad}- {}\n`;
        }
      } else if (Array.isArray(item)) {
        result += `${pad}- ${jsonToYaml(item, indent + 1, false)}`;
      } else {
        result += `${pad}- ${yamlScalar(item)}\n`;
      }
    }
    return result;
  }

  return `${yamlScalar(value)}\n`;
}

// ============================================================
// Express handlers for /openapi.json and /openapi.yaml
// ============================================================

/**
 * Creates an Express handler that returns the OpenAPI spec as JSON.
 *
 * @param spec — the pre-built OpenAPI specification object
 */
export function openApiJsonHandler(spec: Record<string, unknown>): RequestHandler {
  const json = JSON.stringify(spec, null, 2);
  return (_req, res) => {
    res.setHeader('Content-Type', 'application/json');
    res.send(json);
  };
}

/**
 * Creates an Express handler that returns the OpenAPI spec as YAML.
 *
 * @param spec — the pre-built OpenAPI specification object
 */
export function openApiYamlHandler(spec: Record<string, unknown>): RequestHandler {
  const yaml = jsonToYaml(spec);
  return (_req, res) => {
    res.setHeader('Content-Type', 'application/x-yaml');
    res.send(yaml);
  };
}
