// ============================================================
// openapi/openapi.ts
// Builds an OpenAPI 3.0 spec from the global registry.
// Mirror of OpenApi.init() / OpenApi.docs in Dart.
// ============================================================

import { apiRegistry } from '../core/registry';

interface OpenApiOptions {
  title: string;
  port: number;
  version?: string;
  description?: string;
  servers?: Array<{ url: string; description?: string }>;
}

/**
 * Builds a full OpenAPI 3.0 specification object from all registered use
 * cases in `apiRegistry`. Called by ModularApi.serve() automatically.
 *
 * Each use case contributes:
 *   - A path entry (e.g. POST /api/users/create)
 *   - requestBody schema from Input.toSchema()
 *   - response schema from Output.toSchema()
 *   - summary and tags from UseCaseDocMeta
 */
export function buildOpenApiSpec(options: OpenApiOptions): Record<string, unknown> {
  const {
    title,
    port,
    version = '0.1.0',
    description = 'Auto-generated by modular-api',
    servers,
  } = options;

  const defaultServers = [
    { url: `http://localhost:${port}`, description: 'Local' },
  ];

  const paths: Record<string, unknown> = {};

  for (const route of apiRegistry.routes) {
    const method = route.method.toLowerCase();
    const path = route.path;

    // Use schemas captured at registration time
    const inputSchema = route.schemas.input;
    const outputSchema = route.schemas.output;

    if (!paths[path]) {
      paths[path] = {};
    }

    (paths[path] as Record<string, unknown>)[method] = {
      summary: route.doc?.summary,
      description: route.doc?.description,
      tags: route.doc?.tags ?? [route.module],
      ...(method !== 'get' && method !== 'delete'
        ? {
            requestBody: {
              required: true,
              content: {
                'application/json': {
                  schema: inputSchema,
                },
              },
            },
          }
        : {
            parameters: _schemaToQueryParams(inputSchema),
          }),
      responses: {
        '200': {
          description: 'Successful response',
          content: {
            'application/json': {
              schema: outputSchema,
            },
          },
        },
        '400': {
          description: 'Validation error',
          content: {
            'application/json': {
              schema: {
                type: 'object',
                properties: { error: { type: 'string' } },
              },
            },
          },
        },
        '500': {
          description: 'Internal server error',
        },
      },
    };
  }

  return {
    openapi: '3.0.0',
    info: { title, version, description },
    servers: servers ?? defaultServers,
    paths,
  };
}

/** Converts a JSON Schema object properties to OpenAPI query parameters */
function _schemaToQueryParams(schema: Record<string, unknown>): unknown[] {
  const properties = (schema['properties'] as Record<string, unknown>) ?? {};
  const required = (schema['required'] as string[]) ?? [];

  return Object.entries(properties).map(([name, propSchema]) => ({
    name,
    in: 'query',
    required: required.includes(name),
    schema: propSchema,
  }));
}
